title: PhotoBooks - Akshit Arora
email: akshit.arora@colorado.edu
description: > # this means to ignore newlines until "baseurl:"
  Photos by Akshit Arora. Mostly, travel, adventure and nature. 
permalink: ':title/'
baseurl: "/adam-blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Akshit Arora # add your name
author-pic: adam-face.jpg
about-author: My name is Akshit Arora. I’m a graduate student at University of Colorado Boulder, specializing in Artificial Intelligence. 

# Contact links
email: akshit.arora@colorado.edu # Add your Email address
phone: +17206187199 # Add your Phone number
website: https://aroraakshit.github.io/ # Add your website, do not add http://
linkedin: aakshit # Add your Linkedin handle
github: aroraakshit # Add your Github handle
twitter: '@AkshitArora1995' # Add your Twitter handle
facebook: AkshitArora1995 # Add your Facebook handle
instagram: akshit1995 # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: akshitarora-github-io  # Add your discus identifier

# Tracker
analytics: UA-109066326-1 # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
